# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|

  config.vm.define 'ubuntu' do |u|
    u.vm.box = 'bento/ubuntu-18.04'

    # Prevent vbguest plugin from installing latest guest additions
    u.vbguest.auto_update = false if Vagrant.has_plugin?('vagrant-vbguest')

    u.vm.network :private_network, type: 'dhcp'
    u.vm.network "forwarded_port", guest: 80, host: 3080
    u.vm.network "forwarded_port", guest: 4000, host: 3400

    u.vm.synced_folder "./", "/vagrant"

    u.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--memory', '2048']
      vb.customize ['modifyvm', :id, '--cpuexecutioncap', '80']
    end
  end
end
