# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|

  config.vm.define 'centos7' do |c7|
    c7.vm.box = 'bento/centos-7.6'

    # Prevent vbguest plugin from installing latest guest additions
    c7.vbguest.auto_update = false if Vagrant.has_plugin?('vagrant-vbguest')

    c7.vm.network :private_network, type: 'dhcp'
    c7.vm.network "forwarded_port", guest: 80, host: 3080
    c7.vm.network "forwarded_port", guest: 4000, host: 3400

    c7.vm.synced_folder "./", "/vagrant"

    c7.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--memory', '2048']
      vb.customize ['modifyvm', :id, '--cpuexecutioncap', '80']
    end
  end
end
